config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Ticketes, at: "/projects/:project_id/ticketes"
    end
    
    resources :projects, only: [] do
      resources :ticketes
    end
  end

  root "projects#index"

  devise_for :users

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :ticketes do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :ticketes, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tickete.rb
class Tickete < ApplicationRecord
  belongs_to :project
  belongs_to :author, class_name: "User" # assign author to the user model
  belongs_to :state, optional: true
  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, distinct: true
  has_and_belongs_to_many :watchers, join_table: "tickete_watchers",
    class_name: "User", distinct: true
  
  attr_accessor :tag_names

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  before_create :assign_default_state
  after_create :author_watches_me

  # searcher do
  #   label :tag, from: :tags, field: "name"
  # end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end

  private

  def author_watches_me
    if author.email.present? && !self.watchers.include?(author)
      self.watchers << author
    end
  end

  def assign_default_state
    self.state ||= State.default
  end
end

app/controllers/api/ticketes_controller.rb
class API::TicketesController < API::ApplicationController
  before_action :set_project

  def show
    @tickete = @project.ticketes.find(params[:id])
    authorize @tickete, :show?
    render json: @tickete
  end

  def create
    @tickete = @project.ticketes.build(tickete_params)
    authorize @tickete, :create?
    if @tickete.save
      render json: @tickete, status: 201
    else
      render json: { errors: @tickete.errors.full_messages }, status: 422
    end
  end

  private

  def tickete_params
    params.require(:tickete).permit(:name, :description, :author_id)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/api/v2/ticketes.rb
require "sinatra"

module API
  module V2
    class Ticketes < Sinatra::Base
      before do
        headers "Content-Type" => "text/json"
        set_user
        set_project
      end

      get "/:id" do
        tickete = @project.ticketes.find(params[:id])
        unless TicketePolicy.new(@user, tickete).show?
          halt 404, "The tickete you were looking for could not be found."
        end
        TicketeSerializer.new(tickete).to_json
      end

      private

      def set_user
        if env["HTTP_AUTHORIZATION"].present?
          if auth_token = /Token token=(.*)/.match(env["HTTP_AUTHORIZATION"])
            @user = User.find_by(api_key: auth_token[1])
            return @user if @user.present?
          end
        end

        unauthenticated!
      end

      def unauthenticated!
        halt 401, { error: "Unauthenticated"}.to_json
      end

      def set_project
        @project = Project.find(params[:project_id])
      end

      def params
        hash = env["action_dispatch.request.path_parameters"].merge!(super)
        HashWithIndifferentAccess.new(hash)
      end
    end
  end
end

app/controllers/ticketes_controller.rb
class TicketesController < ApplicationController
  before_action :set_project
  before_action :set_tickete, only: [:show, :edit, :update, :destroy, :watch]

  def search
    authorize @project, :show?
    # if params[:search].present?
    #   @ticketes = @project.ticketes.where(id: "#{params[:search]}%")
    # else
    #   @ticketes = @project.ticketes
    # end
    render "projects/show"
  end

  def watch
    authorize @tickete, :show?
    if @tickete.watchers.exists?(current_user.id)
      @tickete.watchers.destroy(current_user)
      flash[:notice] = "You are no longer watching this tickete."
    else
      @tickete.watchers << current_user
      flash[:notice] = "You are now watching this tickete."
    end
    redirect_to project_tickete_path(@tickete.project, @tickete)
  end

  def new
    @tickete = @project.ticketes.build
    authorize @tickete, :create?
    @tickete.attachments.build
  end

  def create
    @tickete = @project.ticketes.new
    whitelisted_params = tickete_params
    unless policy(@tickete).tag?
      whitelisted_params.delete(:tag_names)
    end

    @tickete.attributes = whitelisted_params
    @tickete.author = current_user
    authorize @tickete, :create?

    if @tickete.save
      flash[:notice] = "Tickete has been created."
      redirect_to [@project, @tickete]
    else
      flash.now[:alert] = "Tickete has not been created."
      render "new"
    end
  end

  def show
    authorize @tickete, :show?
    @comment = @tickete.comments.build(state_id: @tickete.state_id)

    respond_to do |format|
      format.html
      format.json { render json: @tickete}
    end
  end

  def edit
    authorize @tickete, :update?
  end

  def update
    authorize @tickete, :update?

    if @tickete.update(tickete_params)
      flash[:notice] = "Tickete has been updated."
      redirect_to [@project, @tickete]
    else
      flash.now[:alert] = "Tickete has not been updated."
      render "edit"
    end
  end

  def destroy
    authorize @tickete, :destroy?

    @tickete.destroy
    flash[:notice] = "Tickete has been deleted."

    redirect_to @project
  end

  private

  def tickete_params
    params.require(:tickete).permit(:name, :description, :tag_names, attachments_attributes: [:file, :file_cache])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_tickete
    @tickete = @project.ticketes.find(params[:id])
  end
end

app/helpers/ticketes_helper.rb
module TicketesHelper
  def state_transition_for(comment)
    if comment.previous_state != comment.state
      content_tag(:p) do
        value = "<strong><i class='fa fa-gear'></i> state changed</strong>"
        if comment.previous_state.present?
          value += " from #{render comment.previous_state}"
        end
        value += " to #{render comment.state}"
        value.html_safe
      end
    end
  end

  def toggle_watching_button(tickete)
    text = if tickete.watchers.include?(current_user)
      "Unwatch"
    else
      "Watch"
    end
    link_to text, watch_project_tickete_path(tickete.project, tickete),
      class: text.parameterize, method: :post
  end
end

app/views/ticketes/_form.html.erb
<%= simple_form_for([project, tickete]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= render "tags/form", f: f %>

  <div id="attachments">
    <h3>Attachments</h3>
    <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
  </div>

  <p>
    <%= link_to "Add another file", new_attachment_path, remote: true,
      id: "add_file", data: { params: { index: tickete.attachments.size }.to_param } %>
  </p>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/ticketes/edit.html.erb
<header>
  <h1>
  Edit Tickete
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, tickete: @tickete %>

app/views/ticketes/new.html.erb
<header>
  <h1>
  New Tickete
  <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, tickete: @tickete %>

app/views/ticketes/show.html.erb
<div id="tickete">
  <header>
    <h1><%= @project.name %></h1>
  </header>

  <header>
    <h2><%= @tickete.name %></h2>

    <ul class="actions">
      <% if policy(@tickete).update? %>
        <li>
          <%= link_to "Edit Tickete", [:edit, @project, @tickete], class: "edit" %>
        </li>
      <% end %>
      <% if policy(@tickete).destroy? %>
        <li>
          <%= link_to "Delete Tickete",
          [@project, @tickete],
          method: :delete,
          data: { confirm: "are you sure you want to delete this tickete?" },
          class: "delete" %>
        </li>
      <% end %>
    </ul>
  </header>

  <table id="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @tickete.author.email %></td>
    </tr>
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@tickete.created_at) %> ago</td>
    </tr>

    <% if @tickete.state.present? %>
      <tr>
        <th>State:</th>
        <td><%= render @tickete.state %></td>
      </tr>
    <% end %>

    <% if @tickete.tags.any? %>
      <tr id="tags">
        <th>Tags:</th>
        <td><%= render @tickete.tags, tickete: @tickete %></td>
      </tr>
    <% end %>

    <tr id="watchers">
      <th>Watchers:</th>
      <td>
        <%= toggle_watching_button(@tickete) %><br />
        <%= @tickete.watchers.map(&:email).to_sentence %>
      </td>
    </tr>
  </table>

  <%= simple_format(@tickete.description) %>

  <% if @tickete.attachments.any? %>
    <h4>Attachments</h4>
    <div class="attachments">
      <% @tickete.attachments.each do |attachment| %>
        <p>
          <%= link_to File.basename(attachment.file.url), attachment_path(attachment) %>
          (<%= number_to_human_size(attachment.file.size) %>)
        </p>
      <% end %>
    </div>
  <% end %>
  
</div>

<header>
  <h3>Comments</h3>
</header>

<div id="comments">
  <% if @tickete.comments.persisted.any? %> 
    <%= render @tickete.comments.persisted %>
  <% else %>
    <p>There are no comments yet.</p>
  <% end %>
</div>

<% if policy(@comment).create? %>
  <%= render "comments/form", tickete: @tickete, comment: @comment %>
<% end %>